# app_single_improved.py
"""
Playful POC: import preview -> sanitize -> commit to GitHub -> attempt to enable Pages
Usage (dev):
  pip install fastapi uvicorn playwright requests python-dotenv
  python -m playwright install
  export PLAYFUL_GH_TOKEN="ghp_xxx"
  export GITHUB_OWNER="playful"
  uvicorn app_single_improved:app --reload --port 3000

Notes:
- This is a POC for development/testing. Run inside a container when exposing publicly.
- The script enforces file-size limits and sanitizes certain JS constructs.
"""
import os
import re
import shutil
import uuid
import json
import base64
import time
from pathlib import Path
from urllib.parse import urlparse
import logging
import tempfile
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from playwright.sync_api import sync_playwright

# Config from env
GITHUB_API = "https://api.github.com"
PLAYFUL_GH_TOKEN = os.getenv("PLAYFUL_GH_TOKEN")
GITHUB_OWNER = os.getenv("GITHUB_OWNER", "playful")
MAX_RESOURCE_SIZE_MB = int(os.getenv("MAX_RESOURCE_SIZE_MB", "30"))  # limit asset download size
IMPORT_TIMEOUT_SECONDS = int(os.getenv("IMPORT_TIMEOUT_SECONDS", "120"))

if not PLAYFUL_GH_TOKEN:
    raise RuntimeError("Set PLAYFUL_GH_TOKEN in environment")

HEADERS = {
    "Authorization": f"token {PLAYFUL_GH_TOKEN}",
    "Accept": "application/vnd.github+json"
}

# logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')

app = FastAPI(title="Playful Import + Commit POC")

class ImportRequest(BaseModel):
    previewUrl: str
    username: str
    project: str
    visibility: str = "public"  # or private

# Utility helpers
def safe_filename(s: str) -> str:
    return re.sub(r'[^a-zA-Z0-9_\-\.]', '_', s)

def to_local_path(webdir: Path, url: str) -> Path:
    try:
        p = urlparse(url)
        host = safe_filename(p.hostname or 'host')
        path = p.path or '/'
        if path.endswith('/') or path == '':
            path = path + 'index.html'
        local = webdir / 'assets' / host / path.lstrip('/')
        return local
    except Exception:
        return webdir / 'assets' / 'unknown' / safe_filename(url)

def download_resource(url: str, dest: Path, timeout=30):
    try:
        dest.parent.mkdir(parents=True, exist_ok=True)
        with requests.get(url, timeout=timeout, stream=True) as r:
            r.raise_for_status()
            total = 0
            with open(dest, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    if not chunk:
                        break
                    total += len(chunk)
                    if total > (MAX_RESOURCE_SIZE_MB * 1024 * 1024):
                        logging.warning("Skipping large resource %s (>%d MB)", url, MAX_RESOURCE_SIZE_MB)
                        return False
                    f.write(chunk)
        return True
    except Exception as e:
        logging.warning("Failed to download %s -> %s", url, e)
        return False

# Sanitizer rudiments
JS_DANGER_PATTERNS = [r'\beval\s*\(', r'new\s+Function\s*\(']

def sanitize_js_file(path: Path):
    try:
        text = path.read_text(encoding='utf8', errors='ignore')
        for pat in JS_DANGER_PATTERNS:
            if re.search(pat, text):
                logging.info("Sanitizing JS file %s", path)
                path.write_text("// sanitized by Playful\n", encoding='utf8')
                return True
    except Exception as e:
        logging.warning("sanitize error %s -> %s", path, e)
    return False

# GitHub helpers (basic)
def ensure_repo(owner: str, repo: str, private=False):
    r = requests.get(f"{GITHUB_API}/repos/{owner}/{repo}", headers=HEADERS)
    if r.status_code == 200:
        return True
    # create in org
    payload = {"name": repo, "private": private, "auto_init": False}
    r2 = requests.post(f"{GITHUB_API}/orgs/{owner}/repos", headers=HEADERS, json=payload)
    if r2.status_code >= 400:
        # fallback: create user repo
        r3 = requests.post(f"{GITHUB_API}/user/repos", headers=HEADERS, json={"name": repo, "private": private})
        if r3.status_code >= 400:
            raise RuntimeError(f"Failed to create repo: {r2.status_code} {r2.text} / {r3.status_code} {r3.text}")
    return True

def get_ref_sha(owner: str, repo: str, branch: str = "main"):
    r = requests.get(f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{branch}", headers=HEADERS)
    if r.status_code == 200:
        return r.json()["object"]["sha"]
    return None

def create_readme_if_missing(owner, repo, branch="main"):
    if get_ref_sha(owner, repo, branch):
        return
    content = base64.b64encode(f"# {repo}\n\nGenerated by Playful".encode()).decode()
    payload = {"message": "init repo", "content": content, "branch": branch}
    r = requests.put(f"{GITHUB_API}/repos/{owner}/{repo}/contents/README.md", headers=HEADERS, json=payload)
    if r.status_code >= 400:
        raise RuntimeError(f"Failed to init repo: {r.status_code} {r.text}")

def read_files_map(local_folder: Path):
    files = {}
    for f in local_folder.rglob("*"):
        if f.is_file():
            rel = f.relative_to(local_folder).as_posix()
            files[rel] = f.read_bytes()
    return files

def bulk_commit(owner: str, repo: str, branch: str, project_folder: str, local_folder: Path, message: str):
    ensure_repo(owner, repo)
    create_readme_if_missing(owner, repo, branch)
    ref_sha = get_ref_sha(owner, repo, branch)
    if not ref_sha:
        raise RuntimeError("Missing branch/ref")
    commit_resp = requests.get(f"{GITHUB_API}/repos/{owner}/{repo}/git/commits/{ref_sha}", headers=HEADERS)
    if commit_resp.status_code >= 400:
        raise RuntimeError(f"Failed to get commit: {commit_resp.status_code} {commit_resp.text}")
    base_tree_sha = commit_resp.json()["tree"]["sha"]

    local_files = read_files_map(local_folder)
    if not local_files:
        raise RuntimeError("No files found to commit")

    tree_items = []
    for rel, content in local_files.items():
        b64 = base64.b64encode(content).decode()
        blob_resp = requests.post(f"{GITHUB_API}/repos/{owner}/{repo}/git/blobs", headers=HEADERS, json={"content": b64, "encoding": "base64"})
        if blob_resp.status_code >= 400:
            logging.warning("Blob create failed for %s: %s", rel, blob_resp.text)
            continue
        blob_sha = blob_resp.json()["sha"]
        path_in_repo = f"{project_folder}/{rel}"
        tree_items.append({"path": path_in_repo, "mode": "100644", "type": "blob", "sha": blob_sha})

    if not tree_items:
        raise RuntimeError("No blobs created successfully")

    tree_payload = {"base_tree": base_tree_sha, "tree": tree_items}
    tree_resp = requests.post(f"{GITHUB_API}/repos/{owner}/{repo}/git/trees", headers=HEADERS, json=tree_payload)
    if tree_resp.status_code >= 400:
        raise RuntimeError(f"create tree failed: {tree_resp.status_code} {tree_resp.text}")
    new_tree_sha = tree_resp.json()["sha"]

    commit_payload = {"message": message, "tree": new_tree_sha, "parents": [ref_sha]}
    commit_resp = requests.post(f"{GITHUB_API}/repos/{owner}/{repo}/git/commits", headers=HEADERS, json=commit_payload)
    if commit_resp.status_code >= 400:
        raise RuntimeError(f"create commit failed: {commit_resp.status_code} {commit_resp.text}")
    new_commit_sha = commit_resp.json()["sha"]

    update_resp = requests.patch(f"{GITHUB_API}/repos/{owner}/{repo}/git/refs/heads/{branch}", headers=HEADERS, json={"sha": new_commit_sha})
    if update_resp.status_code >= 400:
        raise RuntimeError(f"update ref failed: {update_resp.status_code} {update_resp.text}")

    return {"ok": True, "commit_sha": new_commit_sha}

def attempt_enable_pages(owner: str, repo: str):
    try:
        # Enable Pages on repo root => requires Pages permission
        payload = {"source": {"branch": "main", "path": "/"}}
        r = requests.put(f"{GITHUB_API}/repos/{owner}/{repo}/pages", headers=HEADERS, json=payload)
        if r.status_code in (200, 201, 202):
            return {"ok": True, "msg": "Pages likely enabled"}
        logging.warning("Pages enable returned %s: %s", r.status_code, r.text)
        return {"ok": False, "msg": f"Pages API returned {r.status_code} {r.text}"}
    except Exception as e:
        logging.warning("Pages enable exception %s", e)
        return {"ok": False, "msg": str(e)}

# Importer core
def import_preview_to_web(preview_url: str, webdir: Path):
    if webdir.exists():
        shutil.rmtree(webdir)
    webdir.mkdir(parents=True, exist_ok=True)
    resources = set()

    with sync_playwright() as pw:
        browser = pw.chromium.launch(args=['--no-sandbox','--disable-setuid-sandbox'])
        page = browser.new_page()
        def on_response(resp):
            try:
                req = resp.request
                if req.method != "GET": return
                u = resp.url
                if u.startswith("http://") or u.startswith("https://"):
                    if u.startswith("data:"): return
                    resources.add(u)
            except Exception:
                pass
        page.on("response", on_response)

        logging.info("Loading preview URL: %s", preview_url)
        page.goto(preview_url, wait_until="networkidle", timeout=IMPORT_TIMEOUT_SECONDS*1000)
        page.wait_for_timeout(1000)  # small settle time
        html = page.content()
        (webdir / "index.html").write_text(html, encoding='utf8')

        resource_urls = list(resources)
        logging.info("Found %d resources", len(resource_urls))
        # Download resources, small concurrency-ish via slices
        for i in range(0, len(resource_urls), 8):
            batch = resource_urls[i:i+8]
            for u in batch:
                lp = to_local_path(webdir, u)
                download_resource(u, lp, timeout=30)

        # rewrite index.html
        idx_path = webdir / "index.html"
        updated = idx_path.read_text(encoding='utf8')
        for u in resource_urls:
            lp = to_local_path(webdir, u)
            rel = lp.relative_to(webdir).as_posix()
            updated = re.sub(re.escape(u), rel, updated)
        idx_path.write_text(updated, encoding='utf8')

        browser.close()

    # sanitize JS files
    for js in webdir.rglob("*.js"):
        sanitize_js_file(js)

    return webdir

# API endpoint
class ImportBody(BaseModel):
    previewUrl: str
    username: str
    project: str
    visibility: str = "public"

@app.post("/api/import-and-commit")
def import_and_commit(b: ImportBody):
    preview = b.previewUrl
    username = b.username.strip()
    project = b.project.strip().replace(" ", "-").lower()
    visibility = b.visibility

    if not preview or not username or not project:
        raise HTTPException(status_code=400, detail="missing fields")

    # create temp workspace
    wid = str(uuid.uuid4())
    tmpdir = Path(tempfile.gettempdir()) / f"playful_import_{wid}"
    try:
        tmpdir.mkdir(parents=True, exist_ok=True)
        webdir = tmpdir / "web"
        logging.info("Starting import for %s/%s -> workspace %s", username, project, tmpdir)
        # 1) Import preview into webdir
        import_preview_to_web(preview, webdir)

        # basic check: index.html must exist
        idx = webdir / "index.html"
        if not idx.exists():
            raise HTTPException(status_code=500, detail="index.html missing after import")

        # 2) Commit to GitHub
        owner = GITHUB_OWNER
        repo = username
        commit_res = bulk_commit(owner=owner, repo=repo, branch="main", project_folder=project, local_folder=webdir, message=f"Import {project} from {preview}")
        # 3) Attempt to enable Pages (best-effort)
        pages_res = attempt_enable_pages(owner, repo)
        preview_url = f"https://{owner}.github.io/{repo}/{project}/"

        return {"ok": True, "commit": commit_res, "pages": pages_res, "preview_url": preview_url}
    except HTTPException as e:
        raise e
    except Exception as e:
        logging.exception("Import failure")
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        # cleanup workspace
        try:
            if tmpdir.exists():
                shutil.rmtree(tmpdir)
                logging.info("Cleaned up workspace %s", tmpdir)
        except Exception as e:
            logging.warning("Failed cleanup %s -> %s", tmpdir, e)
