services:
  - type: web
    name: playful-importer
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PLAYFUL_GH_TOKEN
        sync: false
      - key: GITHUB_OWNER
        value: playful
